# Generated by Django 4.0.6 on 2022-10-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_subscription_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.CharField(max_length=255)),
                ('company_id', models.CharField(max_length=255)),
                ('subscription_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Company Subscription Admin',
            },
        ),
    ]
