# Generated by Django 4.0.6 on 2022-10-08 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_emails',
            name='company_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company_emails',
            name='subscription_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company_emails',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company_emails',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 8, 12, 52, 18, 680613)),
        ),
    ]
