# Generated by Django 4.0.6 on 2022-10-08 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_company_emails_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_emails',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 8, 13, 21, 1, 496731)),
        ),
        migrations.AlterField(
            model_name='company_emails',
            name='To',
            field=models.EmailField(max_length=255),
        ),
    ]
