# Generated by Django 4.0.6 on 2022-10-08 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_company_emails_time_alter_company_emails_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_emails',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 8, 19, 32, 36, 377476)),
        ),
    ]
