# Generated by Django 3.2.16 on 2022-10-15 13:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_company_emails_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_emails',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 15, 19, 6, 13, 853975)),
        ),
        migrations.CreateModel(
            name='track_mail_open',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='ec5aa3f1a6a0139aa2c6', max_length=255)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.TextField(blank=True, null=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.company_emails')),
            ],
        ),
    ]
