# Generated by Django 3.2.16 on 2022-10-16 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20221015_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_emails',
            name='Opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company_emails',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 16, 16, 38, 46, 735363)),
        ),
        migrations.AlterField(
            model_name='track_mail_open',
            name='key',
            field=models.CharField(default='ca88fffa76321a72c96b', max_length=255),
        ),
    ]
