# Generated by Django 3.2.16 on 2022-10-16 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20221016_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_emails',
            old_name='Opened',
            new_name='Seen',
        ),
        migrations.AddField(
            model_name='company_emails',
            name='Seen_At',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='company_emails',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 16, 18, 38, 13, 756602)),
        ),
        migrations.AlterField(
            model_name='track_mail_open',
            name='key',
            field=models.CharField(default='c4c606764b02dc0af5a1', max_length=255),
        ),
    ]
